const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync(__dirname + '/app.js', 'utf8');
const historySource = source.slice(source.indexOf('class BitrateHistory {'), source.indexOf('const bitrateHistory='));
const BitrateHistory = vm.runInNewContext(historySource + '\nBitrateHistory;');
const history = new BitrateHistory();
history.add(0, {h264:200, mlvc:100});
history.add(1000, {h264:210, mlvc:110});
history.add(2000, {h264:null, mlvc:120});
history.add(3000, {h264:220, mlvc:130});
assert.deepEqual(Array.from(history.segments('h264',3000), group => group.length), [2,1], 'missing data breaks only its series');
assert.equal(history.segments('mlvc',3000)[0].length,4);
history.add(8000, {h264:0, mlvc:Infinity});
assert.deepEqual(Array.from(history.segments('h264',8000), group => group.length), [2,1,1], 'long polling gaps break the curve; real zero is retained');
assert.equal(history.segments('mlvc',8000).length,1, 'invalid readings are omitted');
history.add(31000, {h264:230, mlvc:140});
assert.equal(history.samples[0].time,1000, 'exactly 30 seconds of history are retained');
history.prune(62000);
assert.equal(history.samples.length,0, 'old points expire even without new measurements');
console.log('Bitrate history checks passed');
