mode = "decode"
device = 0
frame_num = -1
format = "none"
input_transport_port = 39191
input_transport_mode = "rtp"
input_transport_payload_type = 96
output_transport_mode = "none"
execution_profile = "pipeline-v1"

[pipeline]
stream_workers = 1
queue_capacity = 3
frame_buffer_slots = 3
entropy_workers = 4
graph_packet_capacity = 2

[model]
manifest = "../mlvc1080p/manifest_decoder_310P1.json"
