mode = "decode"
device = 0
frame_num = -1
format = "none"
input_transport_port = 39191
input_transport_mode = "rtp"
output_transport_mode = "rtsp"
output_transport_rtsp_url = "rtsp://10.195.62.208:8554/mlvc720"
output_transport_rtsp_preset = "ultrafast"
output_transport_rtsp_transport = "udp"
output_transport_rtsp_crf = 0
output_transport_queue_capacity = 3
execution_profile = "pipeline-v1"

[pipeline]
stream_workers = 1
queue_capacity = 3
frame_buffer_slots = 3
entropy_workers = 2
graph_packet_capacity = 2

[model]
manifest = "/root/workplace/mlvc_20260903/mlvc720p/1280x720/manifest_310P1.json"
